In [1]:
import numpy as np
import cv2

In [2]:
face_cascade = cv2.CascadeClassifier('C:/Users/MY DELL/Desktop/face/haarcascade_frontalface_default.xml')
train_happy = cv2.imread('D:\train\Happy')

In [5]:
print(train_happy)

None


In [3]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import model_from_json
json_file = open('modelexpression.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("modelexpression.h5")
print("Loaded model from disk")

Loaded model from disk


In [4]:
def indexmax(a):
    return a.index(max(a))

In [5]:
CATEGORIES = ["Angry", "Happy","Neutral","Sad","Surprise"]
vid=cv2.VideoCapture(0)
IMG_SIZE=224
while True:
    ret,frame=vid.read()
    faces = face_cascade.detectMultiScale(frame, 1.3, 5)
    for (x,y,w,h) in faces:
        frame = cv2.rectangle(frame,(x,y),(x+w+50,y+h+50),(255,0,0),2)
        region=frame[x:x+w+20,y:y+h+20]
        new_array = cv2.resize(region, (IMG_SIZE, IMG_SIZE))
        new_array=np.array(new_array).reshape(-1, IMG_SIZE, IMG_SIZE, 3)
        new_array=new_array/255.0
        print(loaded_model.predict(new_array))
        print(np.argmax(new_array))
        frame=cv2.putText(frame,CATEGORIES[np.argmax(loaded_model.predict(new_array))],(x,y),cv2.FONT_HERSHEY_SIMPLEX ,1,(0,255, 0),2,cv2.LINE_AA)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
    cv2.imshow('frame',frame)
cv2.destroyAllWindows()      

[[0.12564653 0.12328085 0.30839905 0.16247807 0.28019544]]
35616
[[0.0166436  0.83955085 0.09511529 0.01773186 0.03095842]]
135
[[0.00830795 0.8394733  0.11773004 0.00883967 0.02564908]]
84
[[0.00887835 0.85946494 0.10364912 0.0084359  0.01957169]]
81
[[0.22176516 0.13263102 0.14321955 0.18307416 0.31931013]]
43791
[[0.18346266 0.19006285 0.17890713 0.19461846 0.25294888]]
47061
[[0.17121223 0.19908956 0.26404426 0.14915718 0.21649672]]
73974
[[0.13995405 0.23124793 0.3166167  0.12246782 0.18971345]]
78651
[[0.12232246 0.23703593 0.32954434 0.13117349 0.17992379]]
84036
[[0.13663088 0.22859812 0.3133773  0.1263336  0.1950601 ]]
98877
[[0.13888727 0.24834107 0.298066   0.11963098 0.19507475]]
90750
[[0.14463231 0.22273225 0.3107389  0.13305455 0.18884197]]
85416
[[0.14042166 0.24529536 0.2836912  0.13526307 0.19532874]]
71277
[[0.15245013 0.21892947 0.29127735 0.13638975 0.20095327]]
79326
[[0.1302277  0.23799108 0.30152336 0.12932314 0.20093481]]
94848
[[0.15038303 0.21684179 0.3038759

[[0.1621146  0.18701813 0.21094811 0.1698464  0.27007276]]
411
[[0.15667523 0.19116282 0.20705526 0.17980556 0.26530102]]
420
[[0.15775888 0.19680011 0.21865892 0.16298261 0.26379952]]
408
[[0.17290127 0.19653489 0.20727615 0.1772741  0.2460135 ]]
426
[[0.15687044 0.21350068 0.20986865 0.16185161 0.25790855]]
435
[[0.16010049 0.17670919 0.22504997 0.17648382 0.2616565 ]]
402
[[0.15193774 0.2044507  0.2288179  0.1655814  0.24921228]]
405
[[0.16136609 0.2236697  0.21063846 0.17362407 0.23070177]]
435
[[0.15205348 0.23915665 0.21441224 0.1901949  0.20418274]]
459
[[0.15103659 0.25460762 0.18650141 0.21926261 0.1885918 ]]
28604
[[0.17796317 0.22345008 0.1905989  0.15388684 0.25410098]]
19215
[[0.14383243 0.23716952 0.18541634 0.22239877 0.21118298]]
23895
[[0.20825233 0.18404715 0.20799007 0.1621394  0.23757105]]
510
[[0.21448392 0.18972005 0.24435815 0.12591785 0.2255201 ]]
441
[[0.21300015 0.16663697 0.2294568  0.19437693 0.19652914]]
513
[[0.19121908 0.13783053 0.23258862 0.20718996 0.2